# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\src\tiled\newmapdialog.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewMapDialog(object):
    def setupUi(self, NewMapDialog):
        NewMapDialog.setObjectName("NewMapDialog")
        NewMapDialog.resize(371, 323)
        self.gridLayout_3 = QtWidgets.QGridLayout(NewMapDialog)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(NewMapDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.mapWidth = QtWidgets.QSpinBox(self.groupBox_3)
        self.mapWidth.setMinimum(1)
        self.mapWidth.setMaximum(99999)
        self.mapWidth.setProperty("value", 100)
        self.mapWidth.setObjectName("mapWidth")
        self.gridLayout_2.addWidget(self.mapWidth, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.mapHeight = QtWidgets.QSpinBox(self.groupBox_3)
        self.mapHeight.setMinimum(1)
        self.mapHeight.setMaximum(99999)
        self.mapHeight.setProperty("value", 100)
        self.mapHeight.setObjectName("mapHeight")
        self.gridLayout_2.addWidget(self.mapHeight, 1, 1, 1, 1)
        self.pixelSizeLabel = QtWidgets.QLabel(self.groupBox_3)
        self.pixelSizeLabel.setText("3200 x 3200 pixels")
        self.pixelSizeLabel.setObjectName("pixelSizeLabel")
        self.gridLayout_2.addWidget(self.pixelSizeLabel, 2, 0, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(NewMapDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.tileWidth = QtWidgets.QSpinBox(self.groupBox_2)
        self.tileWidth.setMinimum(1)
        self.tileWidth.setMaximum(9999)
        self.tileWidth.setProperty("value", 32)
        self.tileWidth.setObjectName("tileWidth")
        self.gridLayout.addWidget(self.tileWidth, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.tileHeight = QtWidgets.QSpinBox(self.groupBox_2)
        self.tileHeight.setMinimum(1)
        self.tileHeight.setMaximum(9999)
        self.tileHeight.setProperty("value", 32)
        self.tileHeight.setObjectName("tileHeight")
        self.gridLayout.addWidget(self.tileHeight, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewMapDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(NewMapDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.orientation = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orientation.sizePolicy().hasHeightForWidth())
        self.orientation.setSizePolicy(sizePolicy)
        self.orientation.setObjectName("orientation")
        self.gridLayout_4.addWidget(self.orientation, 0, 1, 1, 1)
        self.layerFormatLabel = QtWidgets.QLabel(self.groupBox)
        self.layerFormatLabel.setObjectName("layerFormatLabel")
        self.gridLayout_4.addWidget(self.layerFormatLabel, 1, 0, 1, 1)
        self.layerFormat = QtWidgets.QComboBox(self.groupBox)
        self.layerFormat.setObjectName("layerFormat")
        self.gridLayout_4.addWidget(self.layerFormat, 1, 1, 1, 1)
        self.renderOrderLabel = QtWidgets.QLabel(self.groupBox)
        self.renderOrderLabel.setObjectName("renderOrderLabel")
        self.gridLayout_4.addWidget(self.renderOrderLabel, 2, 0, 1, 1)
        self.renderOrder = QtWidgets.QComboBox(self.groupBox)
        self.renderOrder.setObjectName("renderOrder")
        self.gridLayout_4.addWidget(self.renderOrder, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 2)
        self.label.setBuddy(self.mapWidth)
        self.label_2.setBuddy(self.mapHeight)
        self.label_3.setBuddy(self.tileWidth)
        self.label_4.setBuddy(self.tileHeight)
        self.label_5.setBuddy(self.orientation)
        self.layerFormatLabel.setBuddy(self.layerFormat)
        self.renderOrderLabel.setBuddy(self.renderOrder)

        self.retranslateUi(NewMapDialog)
        self.buttonBox.accepted.connect(NewMapDialog.accept)
        self.buttonBox.rejected.connect(NewMapDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NewMapDialog)
        NewMapDialog.setTabOrder(self.orientation, self.mapWidth)
        NewMapDialog.setTabOrder(self.mapWidth, self.mapHeight)
        NewMapDialog.setTabOrder(self.mapHeight, self.tileWidth)
        NewMapDialog.setTabOrder(self.tileWidth, self.tileHeight)
        NewMapDialog.setTabOrder(self.tileHeight, self.buttonBox)

    def retranslateUi(self, NewMapDialog):
        _translate = QtCore.QCoreApplication.translate
        NewMapDialog.setWindowTitle(_translate("NewMapDialog", "New Map"))
        self.groupBox_3.setTitle(_translate("NewMapDialog", "Map size"))
        self.label.setText(_translate("NewMapDialog", "Width:"))
        self.mapWidth.setSuffix(_translate("NewMapDialog", " tiles"))
        self.label_2.setText(_translate("NewMapDialog", "Height:"))
        self.mapHeight.setSuffix(_translate("NewMapDialog", " tiles"))
        self.groupBox_2.setTitle(_translate("NewMapDialog", "Tile size"))
        self.label_3.setText(_translate("NewMapDialog", "Width:"))
        self.tileWidth.setSuffix(_translate("NewMapDialog", " px"))
        self.label_4.setText(_translate("NewMapDialog", "Height:"))
        self.tileHeight.setSuffix(_translate("NewMapDialog", " px"))
        self.groupBox.setTitle(_translate("NewMapDialog", "Map"))
        self.label_5.setText(_translate("NewMapDialog", "Orientation:"))
        self.layerFormatLabel.setText(_translate("NewMapDialog", "Tile layer format:"))
        self.renderOrderLabel.setText(_translate("NewMapDialog", "Tile render order:"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewMapDialog = QtWidgets.QDialog()
    ui = Ui_NewMapDialog()
    ui.setupUi(NewMapDialog)
    NewMapDialog.show()
    sys.exit(app.exec_())

