# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\src\tiled\newtilesetdialog.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewTilesetDialog(object):
    def setupUi(self, NewTilesetDialog):
        NewTilesetDialog.setObjectName("NewTilesetDialog")
        NewTilesetDialog.resize(387, 314)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewTilesetDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tilesetGroupBox = QtWidgets.QGroupBox(NewTilesetDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tilesetGroupBox.sizePolicy().hasHeightForWidth())
        self.tilesetGroupBox.setSizePolicy(sizePolicy)
        self.tilesetGroupBox.setObjectName("tilesetGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tilesetGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tilesetType = QtWidgets.QComboBox(self.tilesetGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tilesetType.sizePolicy().hasHeightForWidth())
        self.tilesetType.setSizePolicy(sizePolicy)
        self.tilesetType.setObjectName("tilesetType")
        self.tilesetType.addItem("")
        self.tilesetType.addItem("")
        self.gridLayout_2.addWidget(self.tilesetType, 1, 1, 1, 1)
        self.typeLabel = QtWidgets.QLabel(self.tilesetGroupBox)
        self.typeLabel.setObjectName("typeLabel")
        self.gridLayout_2.addWidget(self.typeLabel, 1, 0, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.tilesetGroupBox)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_2.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.tilesetGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name.sizePolicy().hasHeightForWidth())
        self.name.setSizePolicy(sizePolicy)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.tilesetGroupBox)
        self.imageGroupBox = QtWidgets.QGroupBox(NewTilesetDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageGroupBox.sizePolicy().hasHeightForWidth())
        self.imageGroupBox.setSizePolicy(sizePolicy)
        self.imageGroupBox.setCheckable(False)
        self.imageGroupBox.setObjectName("imageGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.imageGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.sourceLabel = QtWidgets.QLabel(self.imageGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourceLabel.sizePolicy().hasHeightForWidth())
        self.sourceLabel.setSizePolicy(sizePolicy)
        self.sourceLabel.setObjectName("sourceLabel")
        self.gridLayout.addWidget(self.sourceLabel, 0, 0, 1, 1)
        self.browseButton = QtWidgets.QPushButton(self.imageGroupBox)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 0, 4, 1, 1)
        self.useTransparentColor = QtWidgets.QCheckBox(self.imageGroupBox)
        self.useTransparentColor.setObjectName("useTransparentColor")
        self.gridLayout.addWidget(self.useTransparentColor, 1, 0, 1, 2)
        self.colorButton = ColorButton(self.imageGroupBox)
        self.colorButton.setEnabled(False)
        self.colorButton.setObjectName("colorButton")
        self.gridLayout.addWidget(self.colorButton, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tileHeight = QtWidgets.QSpinBox(self.imageGroupBox)
        self.tileHeight.setMinimum(1)
        self.tileHeight.setMaximum(9999)
        self.tileHeight.setProperty("value", 32)
        self.tileHeight.setObjectName("tileHeight")
        self.gridLayout_3.addWidget(self.tileHeight, 1, 1, 1, 1)
        self.tileHeightLabel = QtWidgets.QLabel(self.imageGroupBox)
        self.tileHeightLabel.setObjectName("tileHeightLabel")
        self.gridLayout_3.addWidget(self.tileHeightLabel, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        self.tileWidth = QtWidgets.QSpinBox(self.imageGroupBox)
        self.tileWidth.setEnabled(True)
        self.tileWidth.setMinimum(1)
        self.tileWidth.setMaximum(9999)
        self.tileWidth.setProperty("value", 32)
        self.tileWidth.setObjectName("tileWidth")
        self.gridLayout_3.addWidget(self.tileWidth, 0, 1, 1, 1)
        self.marginLabel = QtWidgets.QLabel(self.imageGroupBox)
        self.marginLabel.setObjectName("marginLabel")
        self.gridLayout_3.addWidget(self.marginLabel, 0, 3, 1, 1)
        self.margin = QtWidgets.QSpinBox(self.imageGroupBox)
        self.margin.setMinimum(0)
        self.margin.setMaximum(9999)
        self.margin.setProperty("value", 0)
        self.margin.setObjectName("margin")
        self.gridLayout_3.addWidget(self.margin, 0, 4, 1, 1)
        self.spacing = QtWidgets.QSpinBox(self.imageGroupBox)
        self.spacing.setMinimum(0)
        self.spacing.setMaximum(9999)
        self.spacing.setProperty("value", 0)
        self.spacing.setObjectName("spacing")
        self.gridLayout_3.addWidget(self.spacing, 1, 4, 1, 1)
        self.tileWidthLabel = QtWidgets.QLabel(self.imageGroupBox)
        self.tileWidthLabel.setObjectName("tileWidthLabel")
        self.gridLayout_3.addWidget(self.tileWidthLabel, 0, 0, 1, 1)
        self.spacingLabel = QtWidgets.QLabel(self.imageGroupBox)
        self.spacingLabel.setObjectName("spacingLabel")
        self.gridLayout_3.addWidget(self.spacingLabel, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 2, 0, 1, 5)
        self.image = QtWidgets.QLineEdit(self.imageGroupBox)
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 0, 1, 1, 3)
        self.verticalLayout.addWidget(self.imageGroupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewTilesetDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.nameLabel.setBuddy(self.name)

        self.retranslateUi(NewTilesetDialog)
        self.buttonBox.accepted.connect(NewTilesetDialog.tryAccept)
        self.buttonBox.rejected.connect(NewTilesetDialog.reject)
        self.useTransparentColor.toggled['bool'].connect(self.colorButton.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(NewTilesetDialog)
        NewTilesetDialog.setTabOrder(self.name, self.tilesetType)
        NewTilesetDialog.setTabOrder(self.tilesetType, self.image)
        NewTilesetDialog.setTabOrder(self.image, self.browseButton)
        NewTilesetDialog.setTabOrder(self.browseButton, self.useTransparentColor)
        NewTilesetDialog.setTabOrder(self.useTransparentColor, self.colorButton)
        NewTilesetDialog.setTabOrder(self.colorButton, self.tileWidth)
        NewTilesetDialog.setTabOrder(self.tileWidth, self.tileHeight)
        NewTilesetDialog.setTabOrder(self.tileHeight, self.margin)
        NewTilesetDialog.setTabOrder(self.margin, self.spacing)
        NewTilesetDialog.setTabOrder(self.spacing, self.buttonBox)

    def retranslateUi(self, NewTilesetDialog):
        _translate = QtCore.QCoreApplication.translate
        NewTilesetDialog.setWindowTitle(_translate("NewTilesetDialog", "New Tileset"))
        self.tilesetGroupBox.setTitle(_translate("NewTilesetDialog", "Tileset"))
        self.tilesetType.setItemText(0, _translate("NewTilesetDialog", "Based on Tileset Image"))
        self.tilesetType.setItemText(1, _translate("NewTilesetDialog", "Collection of Images"))
        self.typeLabel.setText(_translate("NewTilesetDialog", "Type:"))
        self.nameLabel.setText(_translate("NewTilesetDialog", "&Name:"))
        self.imageGroupBox.setTitle(_translate("NewTilesetDialog", "Image"))
        self.sourceLabel.setText(_translate("NewTilesetDialog", "Source:"))
        self.browseButton.setText(_translate("NewTilesetDialog", "&Browse..."))
        self.useTransparentColor.setText(_translate("NewTilesetDialog", "Use transparent color:"))
        self.tileHeight.setSuffix(_translate("NewTilesetDialog", " px"))
        self.tileHeightLabel.setText(_translate("NewTilesetDialog", "Tile height:"))
        self.tileWidth.setSuffix(_translate("NewTilesetDialog", " px"))
        self.marginLabel.setToolTip(_translate("NewTilesetDialog", "The space at the edges of the tileset."))
        self.marginLabel.setText(_translate("NewTilesetDialog", "Margin:"))
        self.margin.setSuffix(_translate("NewTilesetDialog", " px"))
        self.spacing.setSuffix(_translate("NewTilesetDialog", " px"))
        self.tileWidthLabel.setText(_translate("NewTilesetDialog", "Tile width:"))
        self.spacingLabel.setToolTip(_translate("NewTilesetDialog", "The space between the tiles."))
        self.spacingLabel.setText(_translate("NewTilesetDialog", "Spacing:"))

from colorbutton import ColorButton

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewTilesetDialog = QtWidgets.QDialog()
    ui = Ui_NewTilesetDialog()
    ui.setupUi(NewTilesetDialog)
    NewTilesetDialog.show()
    sys.exit(app.exec_())

