# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\opensource\tiled\src\tiled\preferencesdialog.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.resize(421, 426)
        self.verticalLayout = QtWidgets.QVBoxLayout(PreferencesDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(PreferencesDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.reloadTilesetImages = QtWidgets.QCheckBox(self.groupBox)
        self.reloadTilesetImages.setObjectName("reloadTilesetImages")
        self.gridLayout.addWidget(self.reloadTilesetImages, 1, 0, 1, 2)
        self.enableDtd = QtWidgets.QCheckBox(self.groupBox)
        self.enableDtd.setObjectName("enableDtd")
        self.gridLayout.addWidget(self.enableDtd, 0, 0, 1, 2)
        self.openLastFiles = QtWidgets.QCheckBox(self.groupBox)
        self.openLastFiles.setChecked(True)
        self.openLastFiles.setObjectName("openLastFiles")
        self.gridLayout.addWidget(self.openLastFiles, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.openGL = QtWidgets.QCheckBox(self.groupBox_2)
        self.openGL.setObjectName("openGL")
        self.gridLayout_2.addWidget(self.openGL, 5, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.gridColor = ColorButton(self.groupBox_2)
        self.gridColor.setObjectName("gridColor")
        self.gridLayout_2.addWidget(self.gridColor, 2, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 4, 1, 1)
        self.languageCombo = QtWidgets.QComboBox(self.groupBox_2)
        self.languageCombo.setObjectName("languageCombo")
        self.gridLayout_2.addWidget(self.languageCombo, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.gridFine = QtWidgets.QSpinBox(self.groupBox_2)
        self.gridFine.setMinimum(1)
        self.gridFine.setMaximum(128)
        self.gridFine.setObjectName("gridFine")
        self.gridLayout_2.addWidget(self.gridFine, 3, 3, 1, 1)
        self.objectLineWidth = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.objectLineWidth.setDecimals(1)
        self.objectLineWidth.setMinimum(1.0)
        self.objectLineWidth.setProperty("value", 2.0)
        self.objectLineWidth.setObjectName("objectLineWidth")
        self.gridLayout_2.addWidget(self.objectLineWidth, 4, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(381, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.objectTypesTable = QtWidgets.QTableView(self.groupBox_3)
        self.objectTypesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.objectTypesTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.objectTypesTable.setWordWrap(False)
        self.objectTypesTable.setObjectName("objectTypesTable")
        self.objectTypesTable.horizontalHeader().setHighlightSections(False)
        self.objectTypesTable.verticalHeader().setVisible(False)
        self.objectTypesTable.verticalHeader().setHighlightSections(False)
        self.verticalLayout_4.addWidget(self.objectTypesTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addObjectTypeButton = QtWidgets.QToolButton(self.groupBox_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/22x22/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addObjectTypeButton.setIcon(icon)
        self.addObjectTypeButton.setAutoRaise(True)
        self.addObjectTypeButton.setObjectName("addObjectTypeButton")
        self.horizontalLayout.addWidget(self.addObjectTypeButton)
        self.removeObjectTypeButton = QtWidgets.QToolButton(self.groupBox_3)
        self.removeObjectTypeButton.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/22x22/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeObjectTypeButton.setIcon(icon1)
        self.removeObjectTypeButton.setAutoRaise(True)
        self.removeObjectTypeButton.setObjectName("removeObjectTypeButton")
        self.horizontalLayout.addWidget(self.removeObjectTypeButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.importObjectTypesButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importObjectTypesButton.sizePolicy().hasHeightForWidth())
        self.importObjectTypesButton.setSizePolicy(sizePolicy)
        self.importObjectTypesButton.setObjectName("importObjectTypesButton")
        self.horizontalLayout.addWidget(self.importObjectTypesButton)
        self.exportObjectTypesButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportObjectTypesButton.sizePolicy().hasHeightForWidth())
        self.exportObjectTypesButton.setSizePolicy(sizePolicy)
        self.exportObjectTypesButton.setObjectName("exportObjectTypesButton")
        self.horizontalLayout.addWidget(self.exportObjectTypesButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.autoMapWhileDrawing = QtWidgets.QCheckBox(self.tab_3)
        self.autoMapWhileDrawing.setGeometry(QtCore.QRect(10, 20, 391, 22))
        self.autoMapWhileDrawing.setObjectName("autoMapWhileDrawing")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(PreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_2.setBuddy(self.languageCombo)
        self.label_3.setBuddy(self.gridColor)
        self.label_4.setBuddy(self.gridFine)
        self.label.setBuddy(self.objectLineWidth)

        self.retranslateUi(PreferencesDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.rejected.connect(PreferencesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)
        PreferencesDialog.setTabOrder(self.tabWidget, self.enableDtd)
        PreferencesDialog.setTabOrder(self.enableDtd, self.reloadTilesetImages)
        PreferencesDialog.setTabOrder(self.reloadTilesetImages, self.languageCombo)
        PreferencesDialog.setTabOrder(self.languageCombo, self.gridColor)
        PreferencesDialog.setTabOrder(self.gridColor, self.gridFine)
        PreferencesDialog.setTabOrder(self.gridFine, self.objectLineWidth)
        PreferencesDialog.setTabOrder(self.objectLineWidth, self.openGL)
        PreferencesDialog.setTabOrder(self.openGL, self.buttonBox)
        PreferencesDialog.setTabOrder(self.buttonBox, self.importObjectTypesButton)
        PreferencesDialog.setTabOrder(self.importObjectTypesButton, self.exportObjectTypesButton)
        PreferencesDialog.setTabOrder(self.exportObjectTypesButton, self.autoMapWhileDrawing)
        PreferencesDialog.setTabOrder(self.autoMapWhileDrawing, self.removeObjectTypeButton)
        PreferencesDialog.setTabOrder(self.removeObjectTypeButton, self.addObjectTypeButton)
        PreferencesDialog.setTabOrder(self.addObjectTypeButton, self.objectTypesTable)

    def retranslateUi(self, PreferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        PreferencesDialog.setWindowTitle(_translate("PreferencesDialog", "Preferences"))
        self.groupBox.setTitle(_translate("PreferencesDialog", "Saving and Loading"))
        self.reloadTilesetImages.setText(_translate("PreferencesDialog", "&Reload tileset images when they change"))
        self.enableDtd.setToolTip(_translate("PreferencesDialog", "Not enabled by default since a reference to an external DTD is known to cause problems with some XML parsers."))
        self.enableDtd.setText(_translate("PreferencesDialog", "Include &DTD reference in saved maps"))
        self.openLastFiles.setText(_translate("PreferencesDialog", "Open last files on startup"))
        self.groupBox_2.setTitle(_translate("PreferencesDialog", "Interface"))
        self.openGL.setText(_translate("PreferencesDialog", "Hardware &accelerated drawing (OpenGL)"))
        self.label_2.setText(_translate("PreferencesDialog", "&Language:"))
        self.label_3.setText(_translate("PreferencesDialog", "Grid color:"))
        self.label_4.setText(_translate("PreferencesDialog", "Fine grid divisions:"))
        self.objectLineWidth.setSuffix(_translate("PreferencesDialog", " pixels"))
        self.label.setText(_translate("PreferencesDialog", "Object line width:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PreferencesDialog", "General"))
        self.groupBox_3.setTitle(_translate("PreferencesDialog", "Object Types"))
        self.addObjectTypeButton.setToolTip(_translate("PreferencesDialog", "Add Object Type"))
        self.addObjectTypeButton.setText(_translate("PreferencesDialog", "Add"))
        self.removeObjectTypeButton.setToolTip(_translate("PreferencesDialog", "Remove Selected Object Types"))
        self.removeObjectTypeButton.setText(_translate("PreferencesDialog", "Remove"))
        self.importObjectTypesButton.setText(_translate("PreferencesDialog", "Import..."))
        self.exportObjectTypesButton.setText(_translate("PreferencesDialog", "Export..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PreferencesDialog", "Object Types"))
        self.autoMapWhileDrawing.setText(_translate("PreferencesDialog", "Use Automapping, when drawing into layers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("PreferencesDialog", "Automapping"))

from colorbutton import ColorButton
import tiled_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PreferencesDialog = QtWidgets.QDialog()
    ui = Ui_PreferencesDialog()
    ui.setupUi(PreferencesDialog)
    PreferencesDialog.show()
    sys.exit(app.exec_())

