# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\tiled\src\tiled\resizedialog.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ResizeDialog(object):
    def setupUi(self, ResizeDialog):
        ResizeDialog.setObjectName("ResizeDialog")
        ResizeDialog.resize(242, 402)
        self.verticalLayout = QtWidgets.QVBoxLayout(ResizeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(ResizeDialog)
        self.groupBox.setObjectName("groupBox")
        self._6 = QtWidgets.QGridLayout(self.groupBox)
        self._6.setObjectName("_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self._6.addWidget(self.label_3, 0, 0, 1, 1)
        self.widthSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.widthSpinBox.setMinimum(1)
        self.widthSpinBox.setMaximum(99999)
        self.widthSpinBox.setObjectName("widthSpinBox")
        self._6.addWidget(self.widthSpinBox, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self._6.addWidget(self.label_4, 1, 0, 1, 1)
        self.heightSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.heightSpinBox.setMinimum(1)
        self.heightSpinBox.setMaximum(99999)
        self.heightSpinBox.setObjectName("heightSpinBox")
        self._6.addWidget(self.heightSpinBox, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(ResizeDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self._4 = QtWidgets.QGridLayout(self.groupBox_2)
        self._4.setObjectName("_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self._4.addWidget(self.label_2, 0, 0, 1, 1)
        self.offsetXSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.offsetXSpinBox.setMinimum(-99999)
        self.offsetXSpinBox.setMaximum(99999)
        self.offsetXSpinBox.setObjectName("offsetXSpinBox")
        self._4.addWidget(self.offsetXSpinBox, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self._4.addWidget(self.label, 1, 0, 1, 1)
        self.offsetYSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.offsetYSpinBox.setMinimum(-99999)
        self.offsetYSpinBox.setMaximum(99999)
        self.offsetYSpinBox.setObjectName("offsetYSpinBox")
        self._4.addWidget(self.offsetYSpinBox, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.frame = QtWidgets.QFrame(ResizeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self._5 = QtWidgets.QVBoxLayout(self.frame)
        self._5.setObjectName("_5")
        self.resizeHelper = ResizeHelper(self.frame)
        self.resizeHelper.setObjectName("resizeHelper")
        self._5.addWidget(self.resizeHelper)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(ResizeDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_3.setBuddy(self.widthSpinBox)
        self.label_4.setBuddy(self.heightSpinBox)
        self.label_2.setBuddy(self.offsetXSpinBox)
        self.label.setBuddy(self.offsetYSpinBox)

        self.retranslateUi(ResizeDialog)
        self.buttonBox.accepted.connect(ResizeDialog.accept)
        self.buttonBox.rejected.connect(ResizeDialog.reject)
        self.offsetXSpinBox.valueChanged['int'].connect(self.resizeHelper.setOffsetX)
        self.offsetYSpinBox.valueChanged['int'].connect(self.resizeHelper.setOffsetY)
        self.widthSpinBox.valueChanged['int'].connect(self.resizeHelper.setNewWidth)
        self.heightSpinBox.valueChanged['int'].connect(self.resizeHelper.setNewHeight)
        self.resizeHelper.offsetXChanged['int'].connect(self.offsetXSpinBox.setValue)
        self.resizeHelper.offsetYChanged['int'].connect(self.offsetYSpinBox.setValue)
        QtCore.QMetaObject.connectSlotsByName(ResizeDialog)
        ResizeDialog.setTabOrder(self.widthSpinBox, self.heightSpinBox)
        ResizeDialog.setTabOrder(self.heightSpinBox, self.offsetXSpinBox)
        ResizeDialog.setTabOrder(self.offsetXSpinBox, self.offsetYSpinBox)
        ResizeDialog.setTabOrder(self.offsetYSpinBox, self.buttonBox)

    def retranslateUi(self, ResizeDialog):
        _translate = QtCore.QCoreApplication.translate
        ResizeDialog.setWindowTitle(_translate("ResizeDialog", "Resize"))
        self.groupBox.setTitle(_translate("ResizeDialog", "Size"))
        self.label_3.setText(_translate("ResizeDialog", "Width:"))
        self.label_4.setText(_translate("ResizeDialog", "Height:"))
        self.groupBox_2.setTitle(_translate("ResizeDialog", "Offset"))
        self.label_2.setText(_translate("ResizeDialog", "X:"))
        self.label.setText(_translate("ResizeDialog", "Y:"))

from resizehelper import ResizeHelper

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ResizeDialog = QtWidgets.QDialog()
    ui = Ui_ResizeDialog()
    ui.setupUi(ResizeDialog)
    ResizeDialog.show()
    sys.exit(app.exec_())

